/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class Add_Events extends javax.swing.JFrame {

    /**
     * Creates new form Add_Events
     */
    public Add_Events() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Event_Id = new javax.swing.JLabel();
        txt_Event_Id = new javax.swing.JTextField();
        Event_Name = new javax.swing.JLabel();
        txt_Event_Name = new javax.swing.JTextField();
        btn_Add1 = new javax.swing.JButton();
        Add_Events = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(710, 440));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Event_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Event_Id.setText("Event Id");
        jPanel1.add(Event_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 106, -1));

        txt_Event_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_Event_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Event_IdActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Event_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 150, -1));

        Event_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Event_Name.setText("Event_Name");
        jPanel1.add(Event_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, -1));

        txt_Event_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_Event_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Event_NameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Event_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 150, -1));

        btn_Add1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Add1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Add1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add1.setText("Add");
        btn_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Add1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 100, 30));

        Add_Events.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Add_Events.setText("Add Events");
        jPanel1.add(Add_Events, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 190, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Add_Event1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 176, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Add Eventbg.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Add1ActionPerformed
        String Event_Id = txt_Event_Id.getText();
        String eventName = txt_Event_Name.getText();
        if (eventName == null || eventName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Event Name cannot be empty", "Insert", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            PreparedStatement pst = con.prepareStatement("exec add_event ?,?");
            pst.setString(1,Event_Id);
            pst.setString(2, eventName);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Event Added Successfully", "Insert", JOptionPane.DEFAULT_OPTION);
            //After clear all data
            txt_Event_Id.setText(null);
            txt_Event_Name.setText(null);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "SQL Server Driver not found", "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Add_Events.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Add_Events.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_Add1ActionPerformed

    private void txt_Event_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Event_IdActionPerformed

    private void txt_Event_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Event_NameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard_Users dash = new Dashboard_Users();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Events.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Events().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Events;
    private javax.swing.JLabel Event_Id;
    private javax.swing.JLabel Event_Name;
    private javax.swing.JButton btn_Add1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Event_Id;
    private javax.swing.JTextField txt_Event_Name;
    // End of variables declaration//GEN-END:variables
}
