/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;
import java.awt.Cursor;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class Admin_Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Login_Form
     */
    public Admin_Login_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserName = new javax.swing.JLabel();
        txt_UserName = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        btn_Login = new javax.swing.JButton();
        txt_Password = new javax.swing.JPasswordField();
        CheckBox = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserName.setBackground(new java.awt.Color(255, 255, 0));
        UserName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UserName.setText("UserName");
        UserName.setOpaque(true);
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 110, 30));

        txt_UserName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txt_UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 180, -1));

        Password.setBackground(new java.awt.Color(255, 255, 51));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Password.setText("Password");
        Password.setOpaque(true);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 110, 30));

        btn_Login.setBackground(new java.awt.Color(0, 0, 0));
        btn_Login.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(255, 255, 255));
        btn_Login.setText("Login");
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 560, -1, -1));

        txt_Password.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(txt_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 180, -1));

        CheckBox.setBackground(new java.awt.Color(204, 255, 255));
        CheckBox.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CheckBox.setText("Show Password");
        CheckBox.setOpaque(true);
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/admin-panel.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        // TODO add your handling code here:
        String UserName = txt_UserName.getText();
        String Password = txt_Password.getText();

        if(UserName.equals("Admin") & Password.equals("Admin"))
        {
            JOptionPane.showMessageDialog(null,"Welcome Admin","Confirmation", JOptionPane.INFORMATION_MESSAGE );
            dispose();
            Admin_Dashboard dash = new Admin_Dashboard();
            dash.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"UserName or Password Wrong","Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void txt_UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserNameActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        // TODO add your handling code here:
         if(CheckBox.isSelected()){
            txt_Password.setEchoChar((char)0);
        }
        else{
            txt_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Intro intro = new Intro();
        intro.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txt_Password;
    private javax.swing.JTextField txt_UserName;
    // End of variables declaration//GEN-END:variables
}
