/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Admin_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Dashboard
     */
    public Admin_Dashboard() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Customer_Details = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_Resource_Allocation = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_Communication = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_Place = new javax.swing.JButton();
        Add_Place = new javax.swing.JLabel();
        btn_Event = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_Print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_Billing = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_Services = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btn_Employee_Details = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btn_Report = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Customer_Details.setBackground(new java.awt.Color(255, 204, 204));
        btn_Customer_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Customer details.png"))); // NOI18N
        btn_Customer_Details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Customer_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Customer_DetailsMouseClicked(evt);
            }
        });
        btn_Customer_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Customer_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Customer_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 32, 210, 150));

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Customer Details");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 198, 180, 20));

        btn_Resource_Allocation.setBackground(new java.awt.Color(255, 204, 204));
        btn_Resource_Allocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Resources.png"))); // NOI18N
        btn_Resource_Allocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Resource_Allocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Resource_AllocationMouseClicked(evt);
            }
        });
        btn_Resource_Allocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Resource_AllocationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Resource_Allocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 274, 210, 150));

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Resource Allocation");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 436, -1, 20));

        btn_Communication.setBackground(new java.awt.Color(255, 204, 204));
        btn_Communication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/email.png"))); // NOI18N
        btn_Communication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Communication.setOpaque(true);
        btn_Communication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CommunicationMouseClicked(evt);
            }
        });
        btn_Communication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CommunicationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Communication, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 501, 210, 170));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Communication");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 683, 190, -1));

        btn_Place.setBackground(new java.awt.Color(255, 204, 204));
        btn_Place.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/add-venue.png"))); // NOI18N
        btn_Place.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Place.setOpaque(true);
        btn_Place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PlaceMouseClicked(evt);
            }
        });
        btn_Place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlaceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 507, 220, 170));

        Add_Place.setBackground(new java.awt.Color(255, 255, 0));
        Add_Place.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add_Place.setText("Add Venue");
        Add_Place.setOpaque(true);
        Add_Place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_PlaceMouseClicked(evt);
            }
        });
        getContentPane().add(Add_Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 690, 120, -1));

        btn_Event.setBackground(new java.awt.Color(255, 204, 204));
        btn_Event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/add-event-image.png"))); // NOI18N
        btn_Event.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Event.setOpaque(true);
        btn_Event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EventMouseClicked(evt);
            }
        });
        btn_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EventActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 507, 230, 170));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Add Event");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 689, 120, -1));

        btn_Print.setBackground(new java.awt.Color(255, 204, 204));
        btn_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/print.png"))); // NOI18N
        btn_Print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PrintMouseClicked(evt);
            }
        });
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1079, 30, 220, 150));

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Print Recipt");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 186, -1, -1));

        btn_Billing.setBackground(new java.awt.Color(255, 204, 204));
        btn_Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/bill.png"))); // NOI18N
        btn_Billing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Billing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BillingMouseClicked(evt);
            }
        });
        btn_Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BillingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 267, 220, 150));

        jLabel9.setBackground(new java.awt.Color(255, 255, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Billing");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1219, 429, 80, -1));

        btn_Services.setBackground(new java.awt.Color(255, 204, 204));
        btn_Services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/services.png"))); // NOI18N
        btn_Services.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Services.setOpaque(true);
        btn_Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ServicesMouseClicked(evt);
            }
        });
        btn_Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Services, new org.netbeans.lib.awtextra.AbsoluteConstraints(1079, 501, 220, 170));

        jLabel10.setBackground(new java.awt.Color(255, 255, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("Add Services");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 680, 140, -1));

        btn_Employee_Details.setBackground(new java.awt.Color(255, 204, 204));
        btn_Employee_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Employee logo.png"))); // NOI18N
        btn_Employee_Details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Employee_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Employee_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Employee_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 211, 150));

        jLabel11.setBackground(new java.awt.Color(255, 255, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setText("Employee details");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        btn_Report.setBackground(new java.awt.Color(255, 204, 204));
        btn_Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/report.png"))); // NOI18N
        btn_Report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 230, 150));

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Report");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 92, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Dashboard");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 210, 30));

        btn_Logout.setBackground(new java.awt.Color(255, 0, 0));
        btn_Logout.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setText("Logout");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Admin_Dashboard.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Customer_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Customer_DetailsMouseClicked
        // TODO add your handling code here:
        dispose();
        Customer_Information customer = new Customer_Information();
        customer.setVisible(true);
    }//GEN-LAST:event_btn_Customer_DetailsMouseClicked

    private void btn_Customer_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Customer_DetailsActionPerformed
        // TODO add your handling code here:
        dispose();
        Customer_Information_1 customer = new Customer_Information_1();
        customer.setVisible(true);
    }//GEN-LAST:event_btn_Customer_DetailsActionPerformed

    private void btn_Resource_AllocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Resource_AllocationMouseClicked
        // TODO add your handling code here:
        dispose();
        Resources re = new Resources();
        re.setVisible(true);
    }//GEN-LAST:event_btn_Resource_AllocationMouseClicked

    private void btn_Resource_AllocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Resource_AllocationActionPerformed
        // TODO add your handling code here:
        dispose();
        Resources_1 re = new Resources_1();
        re.setVisible(true);
    }//GEN-LAST:event_btn_Resource_AllocationActionPerformed

    private void btn_CommunicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CommunicationMouseClicked
        // TODO add your handling code here:
        dispose();
        Communication_Tools tool = new Communication_Tools();
        tool.setVisible(true);
    }//GEN-LAST:event_btn_CommunicationMouseClicked

    private void btn_CommunicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CommunicationActionPerformed
        // TODO add your handling code here:
        dispose();
        Communication_Tools_1 tool = new Communication_Tools_1();
        tool.setVisible(true);
    }//GEN-LAST:event_btn_CommunicationActionPerformed

    private void btn_PlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PlaceMouseClicked
        // TODO add your handling code here:
        dispose();
        Add_Venues venue = new Add_Venues();
        venue.setVisible(true);
    }//GEN-LAST:event_btn_PlaceMouseClicked

    private void btn_PlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlaceActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Venues_1 venue = new Add_Venues_1();
        venue.setVisible(true);
    }//GEN-LAST:event_btn_PlaceActionPerformed

    private void Add_PlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_PlaceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_PlaceMouseClicked

    private void btn_EventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EventMouseClicked
        // TODO add your handling code here:
        dispose();
        Add_Events event = new Add_Events();
        event.setVisible(true);
    }//GEN-LAST:event_btn_EventMouseClicked

    private void btn_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EventActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Events_1 event = new Add_Events_1();
        event.setVisible(true);
    }//GEN-LAST:event_btn_EventActionPerformed

    private void btn_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseClicked
        // TODO add your handling code here:
        dispose();
        Print_Recipts print = new Print_Recipts();
        print.setVisible(true);
    }//GEN-LAST:event_btn_PrintMouseClicked

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        // TODO add your handling code here:
        dispose();
        Print_Recipts_1 print = new Print_Recipts_1();
        print.setVisible(true);
    }//GEN-LAST:event_btn_PrintActionPerformed

    private void btn_BillingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BillingMouseClicked
        // TODO add your handling code here:
        dispose();
        Event_Billings bill = new Event_Billings();
        bill.setVisible(true);
    }//GEN-LAST:event_btn_BillingMouseClicked

    private void btn_BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BillingActionPerformed
        // TODO add your handling code here:
        dispose();
        Event_Billings_1 bill = new Event_Billings_1();
        bill.setVisible(true);
    }//GEN-LAST:event_btn_BillingActionPerformed

    private void btn_ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ServicesMouseClicked
        // TODO add your handling code here:
        dispose();
        Service_Detail service = new Service_Detail();
        service.setVisible(true);
    }//GEN-LAST:event_btn_ServicesMouseClicked

    private void btn_ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ServicesActionPerformed
        // TODO add your handling code here:
        dispose();
        Service_Detail_1 service = new Service_Detail_1();
        service.setVisible(true);
    }//GEN-LAST:event_btn_ServicesActionPerformed

    private void btn_Employee_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Employee_DetailsActionPerformed
        // TODO add your handling code here:
        dispose();
        Employee_Detail emp = new Employee_Detail();
        emp.setVisible(true);
    }//GEN-LAST:event_btn_Employee_DetailsActionPerformed

    private void btn_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportActionPerformed
        // TODO add your handling code here:
        dispose();
        Reports report = new Reports();
        report.setVisible(true);
    }//GEN-LAST:event_btn_ReportActionPerformed

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        JOptionPane.showMessageDialog(null,"Logout Successful");
        Admin_Login_Form intro = new Admin_Login_Form();
        intro.setVisible(true);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String UserName = null;
               new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Place;
    private javax.swing.JLabel Name;
    private javax.swing.JButton btn_Billing;
    private javax.swing.JButton btn_Communication;
    private javax.swing.JButton btn_Customer_Details;
    private javax.swing.JButton btn_Employee_Details;
    private javax.swing.JButton btn_Event;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Place;
    private javax.swing.JButton btn_Print;
    private javax.swing.JButton btn_Report;
    private javax.swing.JButton btn_Resource_Allocation;
    private javax.swing.JButton btn_Services;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
