/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ADMIN
 */
public class Customer_Information extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Information
     */
    public Customer_Information() {
        initComponents();
        fetch();
    }
    public void fetch(){
        try
        {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh"); 
           PreparedStatement pst = con.prepareStatement("exec sp_fetch_Customer");
           ResultSet rs = pst.executeQuery();
           Customer_table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Customer_Details = new javax.swing.JLabel();
        Customer_Id = new javax.swing.JLabel();
        txt_Customer_Id = new javax.swing.JTextField();
        Customer_Name = new javax.swing.JLabel();
        txt_Customer_Name = new javax.swing.JTextField();
        Customer_Address = new javax.swing.JLabel();
        txt_Customer_Address = new javax.swing.JTextField();
        txt_Customer_Mobile = new javax.swing.JTextField();
        Customer_Mobile = new javax.swing.JLabel();
        txt_Customer_Mail = new javax.swing.JTextField();
        Customer_Mail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customer_table = new javax.swing.JTable();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_Delete1 = new javax.swing.JButton();
        btn_Delete2 = new javax.swing.JButton();
        txt_Clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Customer Details");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Customer_Details.setBackground(new java.awt.Color(51, 255, 51));
        Customer_Details.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Customer_Details.setText("Customer Details");
        Customer_Details.setOpaque(true);
        getContentPane().add(Customer_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        Customer_Id.setBackground(new java.awt.Color(255, 255, 0));
        Customer_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Id.setText("Customer Id");
        Customer_Id.setOpaque(true);
        getContentPane().add(Customer_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, -1));

        txt_Customer_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Customer_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 153, -1));

        Customer_Name.setBackground(new java.awt.Color(255, 255, 0));
        Customer_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Name.setText("Customer Name");
        Customer_Name.setOpaque(true);
        getContentPane().add(Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 160, -1));

        txt_Customer_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 153, -1));

        Customer_Address.setBackground(new java.awt.Color(255, 255, 0));
        Customer_Address.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Address.setText("Customer Address");
        Customer_Address.setOpaque(true);
        getContentPane().add(Customer_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 180, -1));

        txt_Customer_Address.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Customer_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 153, -1));

        txt_Customer_Mobile.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Customer_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, 160, -1));

        Customer_Mobile.setBackground(new java.awt.Color(255, 255, 51));
        Customer_Mobile.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Mobile.setText("Customer Mobile");
        Customer_Mobile.setOpaque(true);
        getContentPane().add(Customer_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 180, -1));

        txt_Customer_Mail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Customer_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 190, -1));

        Customer_Mail.setBackground(new java.awt.Color(255, 255, 0));
        Customer_Mail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Mail.setText("Customer Mail");
        Customer_Mail.setOpaque(true);
        getContentPane().add(Customer_Mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 150, -1));

        Customer_table.setBackground(new java.awt.Color(102, 255, 255));
        Customer_table.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Customer_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Customer Name", "Customer Address", "Custometr Mobile", "Customer Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Customer_table.setGridColor(new java.awt.Color(255, 204, 51));
        Customer_table.setRowHeight(30);
        Customer_table.setSelectionBackground(new java.awt.Color(255, 153, 0));
        Customer_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Customer_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Customer_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 402, 920, 290));

        btn_Add.setBackground(new java.awt.Color(0, 0, 0));
        btn_Add.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 89, -1));

        btn_Update.setBackground(new java.awt.Color(0, 0, 0));
        btn_Update.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 110, -1));

        btn_Delete.setBackground(new java.awt.Color(0, 0, 0));
        btn_Delete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 110, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        btn_Delete1.setBackground(new java.awt.Color(0, 0, 0));
        btn_Delete1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Delete1.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete1.setText("Delete");
        btn_Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 110, -1));

        btn_Delete2.setBackground(new java.awt.Color(0, 0, 0));
        btn_Delete2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Delete2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete2.setText("Delete");
        btn_Delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Delete2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Delete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 110, -1));

        txt_Clear.setBackground(new java.awt.Color(0, 0, 0));
        txt_Clear.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_Clear.setForeground(new java.awt.Color(255, 255, 255));
        txt_Clear.setText("Clear");
        txt_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Customer details.1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        try
        {
            String Customer_Id = txt_Customer_Id.getText().toString();
            String Customer_Name = txt_Customer_Name.getText().toString();
            String Customer_Address = txt_Customer_Address.getText().toString();
            String Customer_Mobile = txt_Customer_Mobile.getText().toString();
            String Customer_Mail = txt_Customer_Mail.getText().toString();
            if(!Customer_Id.isEmpty() && !Customer_Name.isEmpty() && !Customer_Address.isEmpty() && !Customer_Mobile.isEmpty() && !Customer_Mail.isEmpty()){
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            PreparedStatement pst = con.prepareStatement("exec add_customer ?,?,?,?,?");
            pst.setString(1,Customer_Id);
            pst.setString(2,Customer_Name);
            pst.setString(3,Customer_Address);
            pst.setString(4,Customer_Mobile);
            pst.setString(5,Customer_Mail);
            int i = pst.executeUpdate();
            if(i!=0)
            {
            JOptionPane.showMessageDialog(this, "Customer Added Successfully", "Added", JOptionPane.DEFAULT_OPTION); 
            txt_Customer_Id.setText(null);
            txt_Customer_Name.setText(null);
            txt_Customer_Address.setText(null);
            txt_Customer_Mobile.setText(null);
            txt_Customer_Mail.setText(null);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Something Error","Added",JOptionPane.ERROR_MESSAGE);
            }
            }
            else
            {
                 JOptionPane.showMessageDialog(this,"All fields required","Added",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        fetch();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void Customer_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Customer_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow=Customer_table.getSelectedRow();
        txt_Customer_Id.setText(Customer_table.getValueAt(selectedRow, 0).toString());
        txt_Customer_Name.setText(Customer_table.getValueAt(selectedRow, 1).toString());
        txt_Customer_Address.setText(Customer_table.getValueAt(selectedRow, 2).toString());
        txt_Customer_Mobile.setText(Customer_table.getValueAt(selectedRow, 3).toString());
        txt_Customer_Mail.setText(Customer_table.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_Customer_tableMouseClicked

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            int row = Customer_table.getSelectedRow();
            String value = (Customer_table.getModel().getValueAt(row, 0).toString());
            PreparedStatement pst = con.prepareStatement("exec update_customer ?,?,?,?,?");
            pst.setString(1,txt_Customer_Name.getText());
            pst.setString(2,txt_Customer_Address.getText());
            pst.setString(3,txt_Customer_Mobile.getText());
            pst.setString(4,txt_Customer_Mail.getText());
            pst.setString(5, txt_Customer_Id.getText());
            pst.executeUpdate();
            DefaultTableModel DFT = (DefaultTableModel) Customer_table.getModel();
            DFT.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Updated Details Successfully", "Update", JOptionPane.DEFAULT_OPTION); 
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Fill all the Field", "Error", JOptionPane.ERROR_MESSAGE); 
        }
        fetch();
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            int row = Customer_table.getSelectedRow();
            String value = (Customer_table.getModel().getValueAt(row, 0).toString());
            PreparedStatement pst = con.prepareStatement("exec delete_customer ?");
            pst.setString(1, txt_Customer_Id.getText());
            pst.executeUpdate();
            DefaultTableModel DFT = (DefaultTableModel) Customer_table.getModel();
            DFT.setRowCount(0);
            JOptionPane.showMessageDialog(this, "Row Deleted Successful","Delete",JOptionPane.DEFAULT_OPTION);
            txt_Customer_Id.setText(null);
            txt_Customer_Name.setText(null);
            txt_Customer_Address.setText(null);
            txt_Customer_Mobile.setText(null);
            txt_Customer_Mail.setText(null);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        fetch();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard_Users dash = new Dashboard_Users();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Delete1ActionPerformed

    private void btn_Delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Delete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Delete2ActionPerformed

    private void txt_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ClearActionPerformed
        // TODO add your handling code here:
       txt_Customer_Id.setText(null);
            txt_Customer_Name.setText(null);
            txt_Customer_Address.setText(null);
            txt_Customer_Mobile.setText(null);
            txt_Customer_Mail.setText(null); 
    }//GEN-LAST:event_txt_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Customer_Address;
    private javax.swing.JLabel Customer_Details;
    private javax.swing.JLabel Customer_Id;
    private javax.swing.JLabel Customer_Mail;
    private javax.swing.JLabel Customer_Mobile;
    private javax.swing.JLabel Customer_Name;
    private javax.swing.JTable Customer_table;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Delete1;
    private javax.swing.JButton btn_Delete2;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton txt_Clear;
    private javax.swing.JTextField txt_Customer_Address;
    private javax.swing.JTextField txt_Customer_Id;
    private javax.swing.JTextField txt_Customer_Mail;
    private javax.swing.JTextField txt_Customer_Mobile;
    private javax.swing.JTextField txt_Customer_Name;
    // End of variables declaration//GEN-END:variables
}
