/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Dashboard_Users extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard_Users
     */
    public Dashboard_Users() {
        initComponents();
    }

    Dashboard_Users(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dashboard_User = new javax.swing.JLabel();
        btn_Customer_Details = new javax.swing.JButton();
        btn_Resource_Allocation = new javax.swing.JButton();
        btn_Print = new javax.swing.JButton();
        btn_Billing = new javax.swing.JButton();
        btn_Communication = new javax.swing.JButton();
        btn_Place = new javax.swing.JButton();
        btn_Event = new javax.swing.JButton();
        btn_Services = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Add_Place = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        btn_Logout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard_User.setBackground(new java.awt.Color(0, 255, 255));
        Dashboard_User.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        Dashboard_User.setText("User Dashboard");
        Dashboard_User.setOpaque(true);
        getContentPane().add(Dashboard_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        btn_Customer_Details.setBackground(new java.awt.Color(255, 204, 204));
        btn_Customer_Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Customer details.png"))); // NOI18N
        btn_Customer_Details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Customer_Details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Customer_DetailsMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_Customer_DetailsMouseReleased(evt);
            }
        });
        btn_Customer_Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Customer_DetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Customer_Details, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 200, 150));

        btn_Resource_Allocation.setBackground(new java.awt.Color(255, 204, 204));
        btn_Resource_Allocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Resources.png"))); // NOI18N
        btn_Resource_Allocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Resource_Allocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Resource_AllocationMouseClicked(evt);
            }
        });
        btn_Resource_Allocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Resource_AllocationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Resource_Allocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 210, 150));

        btn_Print.setBackground(new java.awt.Color(255, 204, 204));
        btn_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/print.png"))); // NOI18N
        btn_Print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PrintMouseClicked(evt);
            }
        });
        btn_Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PrintActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, 220, 150));

        btn_Billing.setBackground(new java.awt.Color(255, 204, 204));
        btn_Billing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/bill.png"))); // NOI18N
        btn_Billing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Billing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BillingMouseClicked(evt);
            }
        });
        btn_Billing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BillingActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Billing, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 220, 150));

        btn_Communication.setBackground(new java.awt.Color(255, 204, 204));
        btn_Communication.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/email.png"))); // NOI18N
        btn_Communication.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Communication.setOpaque(true);
        btn_Communication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CommunicationMouseClicked(evt);
            }
        });
        btn_Communication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CommunicationActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Communication, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 200, 150));

        btn_Place.setBackground(new java.awt.Color(255, 204, 204));
        btn_Place.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/add-venue.png"))); // NOI18N
        btn_Place.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Place.setOpaque(true);
        btn_Place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PlaceMouseClicked(evt);
            }
        });
        btn_Place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PlaceActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 220, 170));

        btn_Event.setBackground(new java.awt.Color(255, 204, 204));
        btn_Event.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/add-event-image.png"))); // NOI18N
        btn_Event.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Event.setOpaque(true);
        btn_Event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_EventMouseClicked(evt);
            }
        });
        btn_Event.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EventActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Event, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 230, 170));

        btn_Services.setBackground(new java.awt.Color(255, 204, 204));
        btn_Services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/services.png"))); // NOI18N
        btn_Services.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Services.setOpaque(true);
        btn_Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ServicesMouseClicked(evt);
            }
        });
        btn_Services.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ServicesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Services, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 500, 220, 170));

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Customer Details");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 180, 20));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Resource Allocation");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, 20));

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Billing");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 460, 80, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Print Recipt");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 240, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Communication");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 190, -1));

        Add_Place.setBackground(new java.awt.Color(255, 255, 0));
        Add_Place.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add_Place.setText("Add Venue");
        Add_Place.setOpaque(true);
        Add_Place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_PlaceMouseClicked(evt);
            }
        });
        getContentPane().add(Add_Place, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, 120, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Add Event");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 680, 120, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Add Services");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 680, 140, -1));

        Name.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 40));

        btn_Logout.setBackground(new java.awt.Color(0, 0, 0));
        btn_Logout.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logout.setText("Logout");
        btn_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/Admin_Dashboard.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Customer_DetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Customer_DetailsMouseClicked
        // TODO add your handling code here:
       dispose();
        Customer_Information customer = new Customer_Information();
        customer.setVisible(true);
    }//GEN-LAST:event_btn_Customer_DetailsMouseClicked

    private void btn_Customer_DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Customer_DetailsActionPerformed
        // TODO add your handling code here:
        dispose();
        Customer_Information customer = new Customer_Information();
        customer.setVisible(true);
    }//GEN-LAST:event_btn_Customer_DetailsActionPerformed

    private void btn_Resource_AllocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Resource_AllocationMouseClicked
        // TODO add your handling code here:
        dispose();
        Resources re = new Resources();
        re.setVisible(true);
    }//GEN-LAST:event_btn_Resource_AllocationMouseClicked

    private void btn_Resource_AllocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Resource_AllocationActionPerformed
        // TODO add your handling code here:
        dispose();
        Resources re = new Resources();
        re.setVisible(true);

    }//GEN-LAST:event_btn_Resource_AllocationActionPerformed

    private void btn_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PrintMouseClicked
        // TODO add your handling code here:
        dispose();
        Print_Recipts print = new Print_Recipts();
        print.setVisible(true);
    }//GEN-LAST:event_btn_PrintMouseClicked

    private void btn_PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PrintActionPerformed
        // TODO add your handling code here:
        dispose();
        Print_Recipts print = new Print_Recipts();
        print.setVisible(true);
    }//GEN-LAST:event_btn_PrintActionPerformed

    private void btn_BillingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BillingMouseClicked
        // TODO add your handling code here:
        dispose();
        Event_Billings bill = new Event_Billings();
        bill.setVisible(true);
    }//GEN-LAST:event_btn_BillingMouseClicked

    private void btn_BillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BillingActionPerformed
        // TODO add your handling code here:
        dispose();
        Event_Billings bill = new Event_Billings();
        bill.setVisible(true);
    }//GEN-LAST:event_btn_BillingActionPerformed

    private void btn_CommunicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CommunicationMouseClicked
        // TODO add your handling code here:
        dispose();
        Communication_Tools tool = new Communication_Tools();
        tool.setVisible(true);
    }//GEN-LAST:event_btn_CommunicationMouseClicked

    private void btn_CommunicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CommunicationActionPerformed
        // TODO add your handling code here:
        dispose();
        Communication_Tools tool = new Communication_Tools();
        tool.setVisible(true);
    }//GEN-LAST:event_btn_CommunicationActionPerformed

    private void btn_PlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PlaceMouseClicked
        // TODO add your handling code here:
        dispose();
        Add_Venues venue = new Add_Venues();
        venue.setVisible(true);
    }//GEN-LAST:event_btn_PlaceMouseClicked

    private void btn_PlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PlaceActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Venues venue = new Add_Venues();
        venue.setVisible(true);
    }//GEN-LAST:event_btn_PlaceActionPerformed

    private void btn_EventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EventMouseClicked
        // TODO add your handling code here:
        dispose();
        Add_Events event = new Add_Events();
        event.setVisible(true);
    }//GEN-LAST:event_btn_EventMouseClicked

    private void btn_EventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EventActionPerformed
        // TODO add your handling code here:
        dispose();
        Add_Events event = new Add_Events();
        event.setVisible(true);
    }//GEN-LAST:event_btn_EventActionPerformed

    private void btn_ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ServicesMouseClicked
        // TODO add your handling code here:
        dispose();
        Service_Detail service = new Service_Detail();
        service.setVisible(true);
    }//GEN-LAST:event_btn_ServicesMouseClicked

    private void btn_ServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ServicesActionPerformed
        // TODO add your handling code here:
        dispose();
        Service_Detail service = new Service_Detail();
        service.setVisible(true);
    }//GEN-LAST:event_btn_ServicesActionPerformed

    private void Add_PlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_PlaceMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Add_PlaceMouseClicked

    private void btn_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        JOptionPane.showMessageDialog(null,"Logout Successful");
        Login intro = new Login();
        intro.setVisible(true);
    }//GEN-LAST:event_btn_LogoutActionPerformed

    private void btn_Customer_DetailsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Customer_DetailsMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Customer_DetailsMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Place;
    private javax.swing.JLabel Dashboard_User;
    private javax.swing.JLabel Name;
    private javax.swing.JButton btn_Billing;
    private javax.swing.JButton btn_Communication;
    private javax.swing.JButton btn_Customer_Details;
    private javax.swing.JButton btn_Event;
    private javax.swing.JButton btn_Logout;
    private javax.swing.JButton btn_Place;
    private javax.swing.JButton btn_Print;
    private javax.swing.JButton btn_Resource_Allocation;
    private javax.swing.JButton btn_Services;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
