/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ADMIN
 */
public class Employee_Detail extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Detail
     */
    public Employee_Detail() {
        initComponents();
        fetch();
    }
    public void fetch(){
        try
        {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh"); 
           PreparedStatement pst = con.prepareStatement("exec sp_fetch_Employee");
           ResultSet rs = pst.executeQuery();
           Employee_Table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Id = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txt_Employee_Name = new javax.swing.JTextField();
        Employee_Name = new javax.swing.JLabel();
        Employee_Address = new javax.swing.JLabel();
        txt_Employee_Address = new javax.swing.JTextField();
        Employee_Mobile = new javax.swing.JLabel();
        txt_Employee_Mobile = new javax.swing.JTextField();
        Employee_Salary = new javax.swing.JLabel();
        txt_Employee_Salary = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Employee_Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Employee Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        Id.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Id.setForeground(new java.awt.Color(255, 51, 0));
        Id.setText("Id");
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 190, -1));

        txt_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 160, -1));

        txt_Employee_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Employee_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 180, -1));

        Employee_Name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Employee_Name.setForeground(new java.awt.Color(255, 51, 0));
        Employee_Name.setText("Employee Name");
        getContentPane().add(Employee_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 180, 180, -1));

        Employee_Address.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Employee_Address.setForeground(new java.awt.Color(255, 51, 0));
        Employee_Address.setText("Employee Address");
        getContentPane().add(Employee_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 190, -1));

        txt_Employee_Address.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Employee_Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 160, -1));

        Employee_Mobile.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Employee_Mobile.setForeground(new java.awt.Color(255, 51, 0));
        Employee_Mobile.setText("Employee Mobile");
        getContentPane().add(Employee_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 230, 180, -1));

        txt_Employee_Mobile.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Employee_Mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 230, 180, -1));

        Employee_Salary.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Employee_Salary.setForeground(new java.awt.Color(255, 51, 0));
        Employee_Salary.setText("Employee Salary");
        getContentPane().add(Employee_Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 190, -1));

        txt_Employee_Salary.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Employee_Salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 160, -1));

        btn_Add.setBackground(new java.awt.Color(0, 0, 0));
        btn_Add.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Add.setForeground(new java.awt.Color(255, 255, 255));
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 110, -1));

        btn_Update.setBackground(new java.awt.Color(0, 0, 0));
        btn_Update.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Update.setForeground(new java.awt.Color(255, 255, 255));
        btn_Update.setText("Update");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 390, 110, -1));

        btn_Delete.setBackground(new java.awt.Color(0, 0, 0));
        btn_Delete.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 390, 110, -1));

        Employee_Table.setBackground(new java.awt.Color(102, 255, 204));
        Employee_Table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Employee_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Employee Name", "Employee Address", "Employee Mobile", "Employee Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Employee_Table.setRowHeight(30);
        Employee_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Employee_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Employee_Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 765, 227));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/employeebg1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin_Dashboard dash = new Admin_Dashboard();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        try
        {
            String Id = txt_Id.getText().toString();
            String Employee_Name = txt_Employee_Name.getText().toString();
            String Employee_Address = txt_Employee_Address.getText().toString();
            String Employee_Mobile = txt_Employee_Mobile.getText().toString();
            //String Employee_Salary = txt_Employee_Salary.getText().toString();
            if(!Employee_Name.isEmpty() && !Employee_Address.isEmpty() && !Employee_Mobile.isEmpty() && !Employee_Salary.getText().toString().isEmpty())
            {
                Float Employee_Salary = Float.parseFloat(txt_Employee_Salary.getText().toString());
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
                PreparedStatement pst = con.prepareStatement("exec add_employee ?,?,?,?,?");
                pst.setString(1,Id);
                pst.setString(2,Employee_Name);
                pst.setString(3,Employee_Address);
                pst.setString(4,Employee_Mobile);
                pst.setFloat(5,Employee_Salary);
                int i = pst.executeUpdate();
                if(i!=0)
                {
                    JOptionPane.showMessageDialog(this,"Employee Added Successfull","insert",JOptionPane.DEFAULT_OPTION);
                    txt_Id.setText(null);
                    txt_Employee_Name.setText(null);
                    txt_Employee_Address.setText(null);
                    txt_Employee_Mobile.setText(null);
                    txt_Employee_Salary.setText(null);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Something Error","insert",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"All fields required","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        fetch();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            int row = Employee_Table.getSelectedRow();
            String value = (Employee_Table.getModel().getValueAt(row, 0).toString());
            PreparedStatement pst = con.prepareStatement("exec update_Employee ?,?,?,?,?");
            pst.setString(1,txt_Employee_Name.getText().toString());
            pst.setString(2,txt_Employee_Address.getText().toString());
            pst.setString(3,txt_Employee_Mobile.getText().toString());
            pst.setString(4,txt_Employee_Salary.getText().toString());
            pst.setString(5,txt_Id.getText().toString());
            int i = pst.executeUpdate();
            DefaultTableModel DFT = (DefaultTableModel) Employee_Table.getModel();
            DFT.setRowCount(0);
            if(i!=0)
            {
                JOptionPane.showMessageDialog(this,"Updated Details Successfull","Update",JOptionPane.DEFAULT_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Row","warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        fetch();
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databaseName=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            int row = Employee_Table.getSelectedRow();
            String value = (Employee_Table.getModel().getValueAt(row, 0).toString());
            PreparedStatement pst = con.prepareStatement("exec delete_Employee ?");
            pst.setString(1,txt_Id.getText().toString());
            int i = pst.executeUpdate();
            DefaultTableModel DFT = (DefaultTableModel) Employee_Table.getModel();
            DFT.setRowCount(0);
            if(i!=0)
            {
                JOptionPane.showMessageDialog(this, "Row Deleted Successful","Delete",JOptionPane.DEFAULT_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please Select Row","warning",JOptionPane.WARNING_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
        fetch();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void Employee_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Employee_TableMouseClicked
        // TODO add your handling code here:
        int selectedRow=Employee_Table.getSelectedRow();
        txt_Id.setText(Employee_Table.getValueAt(selectedRow, 0).toString());
        txt_Employee_Name.setText(Employee_Table.getValueAt(selectedRow, 1).toString());
        txt_Employee_Address.setText(Employee_Table.getValueAt(selectedRow, 2).toString());
        txt_Employee_Mobile.setText(Employee_Table.getValueAt(selectedRow, 3).toString());
        txt_Employee_Salary.setText(Employee_Table.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_Employee_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Employee_Address;
    private javax.swing.JLabel Employee_Mobile;
    private javax.swing.JLabel Employee_Name;
    private javax.swing.JLabel Employee_Salary;
    private javax.swing.JTable Employee_Table;
    private javax.swing.JLabel Id;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Employee_Address;
    private javax.swing.JTextField txt_Employee_Mobile;
    private javax.swing.JTextField txt_Employee_Name;
    private javax.swing.JTextField txt_Employee_Salary;
    private javax.swing.JTextField txt_Id;
    // End of variables declaration//GEN-END:variables
}
