/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;

import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ADMIN
 */
public class Print_Recipts extends javax.swing.JFrame {

    /**
     * Creates new form Print_Recipts
     */
    public Print_Recipts() {
        initComponents();
        fetch1();
    }
     public void fetch1(){
        try
        {
           Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
           Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh"); 
           PreparedStatement pst = con.prepareStatement("exec fetch_Total_Billing_Table");
           ResultSet rs = pst.executeQuery();
           Total_Billing_Table.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }
    public void com_Customer_Name(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            PreparedStatement pst = con.prepareStatement("exec customer_Name");
            ResultSet rs = pst.executeQuery();  
            Com_Customer_Name.removeAllItems();
            while(rs.next()){
              Com_Customer_Name.addItem(rs.getString("customer_Name"));
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
  } 
    public void Com_Mahal_Name(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            PreparedStatement pst = con.prepareStatement("exec resource_Name");
            ResultSet rs = pst.executeQuery();  
            Com_Mahal_Name.removeAllItems();
            while(rs.next()){
              Com_Mahal_Name.addItem(rs.getString("Mahal_Name"));
            }  
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    } 
    public void com_Event_Name(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con=DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
            PreparedStatement pst = con.prepareStatement("exec event_Name");
            ResultSet rs = pst.executeQuery();  
             Com_Event_Name.removeAllItems();
            while(rs.next()){
              //  vector.addElement(new Items(rs.getString("Event_Name")));
              Com_Event_Name.addItem(rs.getString("Event_Name"));
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }  
  } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        btn_Print_Recipt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Total_Billing_Table = new javax.swing.JTable();
        txt_Id = new javax.swing.JTextField();
        Id = new javax.swing.JLabel();
        Resource_Name = new javax.swing.JLabel();
        Com_Mahal_Name = new javax.swing.JComboBox<>();
        Event_Start_date = new javax.swing.JLabel();
        txt_Start_Date = new com.toedter.calendar.JDateChooser();
        Event_End_Date = new javax.swing.JLabel();
        txt_End_Date = new com.toedter.calendar.JDateChooser();
        Customer_Name = new javax.swing.JLabel();
        Com_Customer_Name = new javax.swing.JComboBox<>();
        Event_Name = new javax.swing.JLabel();
        Com_Event_Name = new javax.swing.JComboBox<>();
        txt_Total_Amount1 = new javax.swing.JTextField();
        Gst2 = new javax.swing.JLabel();
        btn_Generate_recipt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, -1, -1));

        area.setColumns(20);
        area.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 421, 480));

        btn_Print_Recipt.setBackground(new java.awt.Color(0, 0, 0));
        btn_Print_Recipt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Print_Recipt.setForeground(new java.awt.Color(255, 255, 255));
        btn_Print_Recipt.setText("Print Recipt");
        btn_Print_Recipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Print_ReciptActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Print_Recipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 560, 187, -1));

        Total_Billing_Table.setBackground(new java.awt.Color(255, 153, 102));
        Total_Billing_Table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Total_Billing_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Build By", "Customer Name", "Mahal Name", "Event Name", "Event Sart Date", "Event End Date", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Total_Billing_Table.setRowHeight(25);
        Total_Billing_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Total_Billing_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Total_Billing_Table);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 52, 860, 310));

        txt_Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 400, 151, -1));

        Id.setBackground(new java.awt.Color(0, 255, 204));
        Id.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Id.setText("Id");
        Id.setOpaque(true);
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 406, 170, -1));

        Resource_Name.setBackground(new java.awt.Color(0, 255, 204));
        Resource_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Resource_Name.setText("Mahal Name");
        Resource_Name.setOpaque(true);
        getContentPane().add(Resource_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 528, 170, -1));

        Com_Mahal_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Com_Mahal_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Com_Mahal_NameActionPerformed(evt);
            }
        });
        getContentPane().add(Com_Mahal_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 525, 149, -1));

        Event_Start_date.setBackground(new java.awt.Color(0, 255, 204));
        Event_Start_date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Event_Start_date.setText("Event Start Date");
        Event_Start_date.setOpaque(true);
        getContentPane().add(Event_Start_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 404, 170, -1));

        txt_Start_Date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Start_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 404, 149, -1));

        Event_End_Date.setBackground(new java.awt.Color(0, 255, 204));
        Event_End_Date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Event_End_Date.setText("Event End Date");
        Event_End_Date.setOpaque(true);
        getContentPane().add(Event_End_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 463, 170, -1));

        txt_End_Date.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_End_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 468, 149, -1));

        Customer_Name.setBackground(new java.awt.Color(0, 255, 204));
        Customer_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Customer_Name.setText("Customer Name");
        Customer_Name.setOpaque(true);
        getContentPane().add(Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 465, 170, -1));

        Com_Customer_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(Com_Customer_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 462, 151, -1));

        Event_Name.setBackground(new java.awt.Color(0, 255, 204));
        Event_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Event_Name.setText("Event Name");
        Event_Name.setOpaque(true);
        getContentPane().add(Event_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 589, 170, -1));

        Com_Event_Name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(Com_Event_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 586, 147, -1));

        txt_Total_Amount1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(txt_Total_Amount1, new org.netbeans.lib.awtextra.AbsoluteConstraints(668, 520, 149, -1));

        Gst2.setBackground(new java.awt.Color(0, 255, 204));
        Gst2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Gst2.setText("Total Amount");
        Gst2.setOpaque(true);
        getContentPane().add(Gst2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 523, 170, -1));

        btn_Generate_recipt.setBackground(new java.awt.Color(0, 0, 0));
        btn_Generate_recipt.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btn_Generate_recipt.setForeground(new java.awt.Color(255, 255, 255));
        btn_Generate_recipt.setText("Generate Recipt");
        btn_Generate_recipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Generate_reciptActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Generate_recipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 187, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/recipt.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1400, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Dashboard_Users dash = new Dashboard_Users();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_Print_ReciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Print_ReciptActionPerformed
        // TODO add your handling code here:
        try
        {
            area.print();
        }
        catch(Exception ex)
        {

        }
    }//GEN-LAST:event_btn_Print_ReciptActionPerformed

    private void Total_Billing_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Total_Billing_TableMouseClicked
        // TODO add your handling code here:
        int selectedRow=Total_Billing_Table.getSelectedRow();
        txt_Id.setText(Total_Billing_Table.getValueAt(selectedRow, 0).toString());
        String com_Customer = Total_Billing_Table.getValueAt(selectedRow,2).toString();
        for(int i=0; i<Com_Customer_Name.getItemCount(); i++){
            if(Com_Customer_Name.getItemAt(i).toString().equalsIgnoreCase(com_Customer)){
                Com_Customer_Name.setSelectedIndex(i);
            }
        }
        String com_Resource = Total_Billing_Table.getValueAt(selectedRow,3).toString();
        for(int i=0; i<Com_Mahal_Name.getItemCount(); i++){
            if(Com_Mahal_Name.getItemAt(i).toString().equalsIgnoreCase(com_Resource)){
                Com_Mahal_Name.setSelectedIndex(i);
            }
        }
        String com_Event = Total_Billing_Table.getValueAt(selectedRow,4).toString();
        for(int i=0; i<Com_Event_Name.getItemCount(); i++){
            if(Com_Event_Name.getItemAt(i).toString().equalsIgnoreCase(com_Event)){
                Com_Event_Name.setSelectedIndex(i);
            }
        }
        txt_Start_Date.setDate((Date) Total_Billing_Table.getValueAt(selectedRow, 5));
        txt_End_Date.setDate((Date) Total_Billing_Table.getValueAt(selectedRow, 6));
        txt_Total_Amount1.setText(Total_Billing_Table.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_Total_Billing_TableMouseClicked

    private void Com_Mahal_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Com_Mahal_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Com_Mahal_NameActionPerformed

    private void btn_Generate_reciptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Generate_reciptActionPerformed
        // TODO add your handling code here:
        area.setText("******************************************\n");
        area.setText(area.getText()+"*                             G Art Event                       *\n");
        area.setText(area.getText()+"******************************************\n");

        Date obj = new Date();
        String date = obj.toString();
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"Customer Name :"+" " + Com_Customer_Name.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"Mahal Name :"+" "+Com_Mahal_Name.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"Event Name :"+" "+Com_Event_Name.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"Event Start Date :"+" "+txt_Start_Date.getDate()+"\n\n");
        area.setText(area.getText()+"Event End Date :"+" "+txt_End_Date.getDate()+"\n\n");
        area.setText(area.getText()+"Total Amount :"+" "+txt_Total_Amount1.getText()+"\n\n");

        area.setText(area.getText()+"***************  Thank You   *****************\n");
    }//GEN-LAST:event_btn_Generate_reciptActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        com_Customer_Name();
        Com_Mahal_Name();
        com_Event_Name();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Print_Recipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Print_Recipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Print_Recipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Print_Recipts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Print_Recipts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Com_Customer_Name;
    private javax.swing.JComboBox<String> Com_Event_Name;
    private javax.swing.JComboBox<String> Com_Mahal_Name;
    private javax.swing.JLabel Customer_Name;
    private javax.swing.JLabel Event_End_Date;
    private javax.swing.JLabel Event_Name;
    private javax.swing.JLabel Event_Start_date;
    private javax.swing.JLabel Gst2;
    private javax.swing.JLabel Id;
    private javax.swing.JLabel Resource_Name;
    private javax.swing.JTable Total_Billing_Table;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btn_Generate_recipt;
    private javax.swing.JButton btn_Print_Recipt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser txt_End_Date;
    private javax.swing.JTextField txt_Id;
    private com.toedter.calendar.JDateChooser txt_Start_Date;
    private javax.swing.JTextField txt_Total_Amount1;
    // End of variables declaration//GEN-END:variables
class Items{
      private String Id; 
     public Items(String Id){
         this.Id = Id;
     }
     @Override
     public String toString(){
         return Id;
     }
}
}
