/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class Send_Codes extends javax.swing.JFrame {
int randomCode;
    /**
     * Creates new form Send_Codes
     */
    public Send_Codes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Enter_Email = new javax.swing.JLabel();
        txt_Enter_Email = new javax.swing.JTextField();
        btn_Send = new javax.swing.JButton();
        Enter_Code = new javax.swing.JLabel();
        txt_Enter_Code = new javax.swing.JTextField();
        btn_Verify_Code = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Enter_Email.setBackground(new java.awt.Color(255, 255, 0));
        Enter_Email.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Enter_Email.setText("Enter Email");
        Enter_Email.setOpaque(true);
        jPanel1.add(Enter_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 120, -1));

        txt_Enter_Email.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(txt_Enter_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 220, -1));

        btn_Send.setBackground(new java.awt.Color(0, 0, 0));
        btn_Send.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Send.setForeground(new java.awt.Color(255, 255, 255));
        btn_Send.setText("Send");
        btn_Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 90, -1));

        Enter_Code.setBackground(new java.awt.Color(255, 255, 0));
        Enter_Code.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Enter_Code.setText("Enter Code");
        Enter_Code.setOpaque(true);
        jPanel1.add(Enter_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, -1));

        txt_Enter_Code.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(txt_Enter_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, -1));

        btn_Verify_Code.setBackground(new java.awt.Color(0, 0, 0));
        btn_Verify_Code.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_Verify_Code.setForeground(new java.awt.Color(255, 255, 255));
        btn_Verify_Code.setText("Verify Code");
        btn_Verify_Code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Verify_CodeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Verify_Code, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 140, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 22, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 651, 407));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/send_code1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login intro = new Login();
        intro.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SendActionPerformed
        // TODO add your handling code here:
        try
        {
            Random rand = new Random();
            randomCode = rand.nextInt(999999);
            String host = "smtp.gmail.com";
            String user = "mkrajesh2000@gmail.com";
            String pass = "oofe sjzc kpov ktre";
            String to = txt_Enter_Email.getText();
            String subject = "Reseting Code";
            String message = "Your reset code is"+randomCode;
            boolean sessionDebug = false;
            Properties pros = System.getProperties();

            pros.put("mail.smtp.auth", "true");
            pros.put("mail.smtp.starttls.enable", "true");
            pros.put("mail.smtp.host", "host");
            pros.put("mail.smtp.port", "587");
            pros.put("mail.smtp.starttls.required", "true");
            Session mailSession = Session.getDefaultInstance(pros,null);
            mailSession.setDebug(sessionDebug);
            Message msg = new MimeMessage(mailSession);
            msg.setFrom(new InternetAddress(user));
            InternetAddress [] address = {new InternetAddress(to)};
            msg.setRecipients(Message.RecipientType.TO, address);
            msg.setSubject(subject);
            msg.setText(message);
            Transport transport = mailSession.getTransport("smtp");
            transport.connect(host,user,pass);
            transport.sendMessage(msg, msg.getAllRecipients());
            transport.close();
            JOptionPane.showMessageDialog(null,"code has been send to the email");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, ex);
        }

    }//GEN-LAST:event_btn_SendActionPerformed

    private void btn_Verify_CodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Verify_CodeActionPerformed
        // TODO add your handling code here:
        if(Integer.valueOf(txt_Enter_Code.getText())==randomCode){
            Rest_Passwords re = new Rest_Passwords(txt_Enter_Email.getText());
            re.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Code do not match");
        }
    }//GEN-LAST:event_btn_Verify_CodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Send_Codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Send_Codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Send_Codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Send_Codes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Send_Codes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Enter_Code;
    private javax.swing.JLabel Enter_Email;
    private javax.swing.JButton btn_Send;
    private javax.swing.JButton btn_Verify_Code;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_Enter_Code;
    private javax.swing.JTextField txt_Enter_Email;
    // End of variables declaration//GEN-END:variables
}
