/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package g_art_event.pkg1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


/**
 *
 * @author ADMIN
 */
public class SignUp_Form extends javax.swing.JFrame {

    /**
     * Creates new form SignUp_Form
     */
    public SignUp_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        SignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        txt_pwd = new javax.swing.JPasswordField();
        txt_uname = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setBackground(new java.awt.Color(255, 255, 153));
        Name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Name.setText("Name");
        Name.setOpaque(true);
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 170, 27));

        txt_name.setBackground(new java.awt.Color(255, 255, 153));
        txt_name.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_name.setOpaque(true);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 187, -1));

        SignUp.setBackground(new java.awt.Color(0, 0, 0));
        SignUp.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        SignUp.setForeground(new java.awt.Color(255, 255, 255));
        SignUp.setText("SignUp");
        SignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("NewUser Form");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        UserName.setBackground(new java.awt.Color(255, 255, 153));
        UserName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        UserName.setText("UserName");
        UserName.setOpaque(true);
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 170, -1));

        Password.setBackground(new java.awt.Color(255, 255, 153));
        Password.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Password.setText("Password");
        Password.setOpaque(true);
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 460, 170, -1));

        txt_pwd.setBackground(new java.awt.Color(255, 255, 153));
        txt_pwd.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_pwd.setOpaque(true);
        txt_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pwdActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 187, -1));

        txt_uname.setBackground(new java.awt.Color(255, 255, 153));
        txt_uname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_uname.setOpaque(true);
        txt_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_unameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 187, -1));

        Email.setBackground(new java.awt.Color(255, 255, 153));
        Email.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Email.setText("Email ");
        Email.setOpaque(true);
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 170, -1));

        txt_email.setBackground(new java.awt.Color(255, 255, 153));
        txt_email.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        txt_email.setOpaque(true);
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 187, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/g_art_event/images/register.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        try
        {
            String Name = txt_name.getText().toString();
            String Email = txt_email.getText().toString();
            String UserName = txt_uname.getText().toString();
            String Password = txt_pwd.getText().toString();
            if(!Name.isEmpty() && !Email.isEmpty() &&!UserName.isEmpty()&& !Password.isEmpty() )
            {

                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-QBNMT1Q;databasename=G_Art_Event_1;TrustServerCertificate=True;user=Rajesh;password=Rajesh");
                PreparedStatement pst = con.prepareStatement("exec sp_adduser1 ?,?,?,?");
                pst.setString(1,Name);
                pst.setString(2,Email);
                pst.setString(3,UserName);
                pst.setString(4,Password);

                int i = pst.executeUpdate();
                if(i!=0)
                {
                    JOptionPane.showMessageDialog(this,"SignUp Successfull","SignUp",JOptionPane.DEFAULT_OPTION);
                    dispose();
                    Login login = new Login();
                    login.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Something Error","SignUp",JOptionPane.ERROR_MESSAGE);
                }

            }else
            {
                JOptionPane.showMessageDialog(this,"All fields required","SignUp",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,ex.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_SignUpActionPerformed

    private void txt_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pwdActionPerformed

    private void txt_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_unameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login dash = new Login();
        dash.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel UserName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JTextField txt_uname;
    // End of variables declaration//GEN-END:variables
}
